import type { Vehicle } from "../types/domain";

export const vehicles: Vehicle[] = [
  { id: "BUS-104", registration: "KA-01-AA-104", type: "Electric Bus", category: "Energy Storage", cargo: "Passengers", depotId: "DEP-BLR", driverId: "DRV-101", location: "Bengaluru Depot", route: "Silk Board to Airport", status: "Active", riskLevel: "Critical", riskScore: 94, lastUpdated: "10:30 AM", assetValueCr: 1.8, complianceScore: 82, coordinates: { x: 54, y: 78 } },
  { id: "TRK-221", registration: "KA-01-BB-221", type: "Battery Truck", category: "Energy Storage", cargo: "Lithium Batteries", depotId: "DEP-GGN", driverId: "DRV-102", location: "Tumkur Highway", route: "Bengaluru to Pune", status: "Active", riskLevel: "High", riskScore: 87, lastUpdated: "10:28 AM", assetValueCr: 1.4, complianceScore: 76, coordinates: { x: 46, y: 64 } },
  { id: "VAN-309", registration: "KA-01-CC-309", type: "Pharma Van", category: "High-Value Cargo", cargo: "Pharmaceuticals", depotId: "DEP-CHN", driverId: "DRV-103", location: "Mysore Road", route: "Chennai to Bengaluru", status: "Active", riskLevel: "Low", riskScore: 22, lastUpdated: "10:26 AM", assetValueCr: 0.9, complianceScore: 94, coordinates: { x: 60, y: 82 } },
  { id: "BUS-187", registration: "KA-01-DD-187", type: "School Bus", category: "Passenger Transport", cargo: "Passengers", depotId: "DEP-LKO", driverId: "DRV-104", location: "Sitapura Road", route: "Lucknow City Loop", status: "Incident", riskLevel: "Critical", riskScore: 91, lastUpdated: "10:25 AM", assetValueCr: 0.6, complianceScore: 68, coordinates: { x: 68, y: 43 } },
  { id: "TRK-120", registration: "KA-01-EE-120", type: "General Cargo Truck", category: "General Cargo", cargo: "Consumer Goods", depotId: "DEP-MUM", driverId: "DRV-105", location: "Nelamangala", route: "Mumbai to Bengaluru", status: "Active", riskLevel: "Medium", riskScore: 58, lastUpdated: "10:23 AM", assetValueCr: 0.5, complianceScore: 88, coordinates: { x: 39, y: 66 } },
  { id: "LPG-412", registration: "DL-1LA-E-1234", type: "LPG Tanker", category: "Explosive Cargo", cargo: "LPG", depotId: "DEP-JAI", driverId: "DRV-106", location: "NH44, Panipat", route: "Jaipur to Panipat", status: "Active", riskLevel: "Critical", riskScore: 92, lastUpdated: "10:22 AM", assetValueCr: 2.1, complianceScore: 79, coordinates: { x: 48, y: 30 } },
  { id: "EVB-510", registration: "TN-09-EV-510", type: "Electric Bus", category: "Energy Storage", cargo: "Passengers", depotId: "DEP-CHN", driverId: "DRV-107", location: "OMR Corridor", route: "Chennai OMR", status: "Active", riskLevel: "Medium", riskScore: 49, lastUpdated: "10:19 AM", assetValueCr: 1.7, complianceScore: 91, coordinates: { x: 62, y: 88 } },
  { id: "CHM-730", registration: "GJ-05-BT-6789", type: "Chemical Tanker", category: "Hazardous Chemicals", cargo: "Industrial Solvent", depotId: "DEP-VAD", driverId: "DRV-108", location: "NH48, Vadodara", route: "Vadodara to Vapi", status: "Active", riskLevel: "Critical", riskScore: 89, lastUpdated: "10:18 AM", assetValueCr: 2.4, complianceScore: 74, coordinates: { x: 27, y: 52 } },
  { id: "FUEL-808", registration: "MH-12-FL-808", type: "Petrol Tanker", category: "Flammable Liquids", cargo: "Petrol", depotId: "DEP-PUN", driverId: "DRV-109", location: "Pune Bypass", route: "Pune to Nashik", status: "Active", riskLevel: "High", riskScore: 74, lastUpdated: "10:16 AM", assetValueCr: 1.2, complianceScore: 84, coordinates: { x: 35, y: 64 } },
  { id: "AMB-222", registration: "UP-32-AM-222", type: "Ambulance", category: "Passenger Transport", cargo: "Patients", depotId: "DEP-LKO", driverId: "DRV-110", location: "Gomti Nagar", route: "Hospital Response", status: "Active", riskLevel: "High", riskScore: 68, lastUpdated: "10:13 AM", assetValueCr: 0.8, complianceScore: 89, coordinates: { x: 69, y: 45 } },
  { id: "COLD-330", registration: "TN-09-CD-1357", type: "Cold Chain Truck", category: "High-Value Cargo", cargo: "Vaccines", depotId: "DEP-CHN", driverId: "DRV-111", location: "NH45, Salem", route: "Chennai to Coimbatore", status: "Maintenance", riskLevel: "Medium", riskScore: 55, lastUpdated: "10:10 AM", assetValueCr: 1.1, complianceScore: 86, coordinates: { x: 55, y: 90 } },
  { id: "MIN-611", registration: "OD-09-MD-611", type: "Mining Dumper", category: "Heavy Equipment", cargo: "Mining Material", depotId: "DEP-CJB", driverId: "DRV-112", location: "Industrial Quarry", route: "Mine Pit 4", status: "Active", riskLevel: "High", riskScore: 72, lastUpdated: "10:09 AM", assetValueCr: 6.5, complianceScore: 81, coordinates: { x: 50, y: 91 } }
];
