class FireRiskConfig:
    """Enterprise Fire Risk Configuration"""

    BATTERY_TEMP_HIGH = 60.0
    CELL_TEMP_HIGH = 75.0
    AMBIENT_TEMP_HIGH = 45.0
    BATTERY_CURRENT_HIGH = 250.0
    BATTERY_VOLTAGE_HIGH = 700.0
    SMOKE_LEVEL_HIGH = 70.0
    GAS_CONCENTRATION_HIGH = 65.0
    LOW_COOLANT_LEVEL = 30.0

    BATTERY_TEMP_SCORE = 35
    CELL_TEMP_SCORE = 20
    AMBIENT_TEMP_SCORE = 10
    BATTERY_CURRENT_SCORE = 10
    BATTERY_VOLTAGE_SCORE = 5
    SMOKE_SCORE = 30
    GAS_SCORE = 25
    COOLANT_SCORE = 15
